language: python
branches:
  only:  # don't build "pushes" except on the master branch
    - master
cache: pip
python:
    - 3.6
    - 3.7
install:
    - make devdeps
    - pip install git+https://github.com/bioforensics/happer.git
    - pip install git+https://github.com/bioforensics/MicroHapDB.git
    - pip install .
script:
    - make test
    - make style
after_success:
    - bash <(curl -s https://codecov.io/bash)
