dist: trusty
language: python
branches:
  only:  # don't build "pushes" except on the master branch
    - master
cache: pip
python:
#    - 3.5
    - 3.6
install:
    - make devdeps
    - pip install git+https://github.com/bioforensics/happer.git
    - pip install git+https://github.com/bioforensics/MicroHapDB.git
    - pip install .
    - mhpl8r getrefr
script:
    - make refr
    - make test
    - make style
after_success:
    - bash <(curl -s https://codecov.io/bash)
