dist: trusty
language: python
branches:
  only:  # don't build "pushes" except on the master branch
    - master
cache: pip
python:
#    - 3.5
    - 3.6
install:
    - make devdeps
    - pip install git+https://github.com/bioforensics/happer.git
    - pip install git+https://github.com/bioforensics/MicroHapDB.git
    - pip install .
    - mhpl8r getrefr
#     For some reason, on TravisCI there's some confusion between the installed package data path and the working package data path
    - bash -c 'ln -s $(mhpl8r getrefr --path)* microhapulator/data/'
script:
    - make test
    - make style
after_success:
    - bash <(curl -s https://codecov.io/bash)
