name: microhapulator-demo
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bash_kernel
  - bwa
  - curl
  - flash
  - git
  - pip
  - pip:
    - git+https://github.com/bioforensics/MicroHapulator.git
  - samtools
