name: CI Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.11", "3.12"]
      fail-fast: false
    steps:
    - name: Check out code
      uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up pixi package manager
      uses: prefix-dev/setup-pixi@v0.8.10
      with:
        pixi-version: v0.48.2
        cache: true
    - name: Install
      run: |
        pixi install
        pixi install -e test
        pixi run mhpl8r getrefr
    - name: Test with pytest
      run: |
        pixi run test
    - name: Style and documentation check
      run: |
        pixi run style
        pixi run docs
